import random

from database.connection import get_connection


ACTIVITIES = [
    (
        "Microsoft Defender Signature Update",
        "Defender",
        "Microsoft Defender"
    ),
    (
        "CrowdStrike Sensor Upgrade",
        "CrowdStrike",
        "CrowdStrike Falcon"
    ),
    (
        "BitLocker Recovery Key Rotation",
        "BitLocker",
        "Microsoft Intune"
    ),
    (
        "TPM Remediation",
        "TPM",
        "PowerShell"
    ),
    (
        "Intune Policy Synchronization",
        "Intune",
        "Microsoft Intune"
    ),
    (
        "ASR Policy Deployment",
        "Security Policy",
        "Microsoft Defender"
    ),
    (
        "Firewall Policy Update",
        "Firewall",
        "Microsoft Defender"
    )
]


def seed_engineering():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT
            device_id,
            risk_score
        FROM devices
        ORDER BY device_id
    """)

    devices = cursor.fetchall()

    total = 0

    for device in devices:

        risk = device["risk_score"]

        if risk <= 25:
            activity_count = random.randint(0, 1)

        elif risk <= 70:
            activity_count = random.randint(1, 2)

        else:
            activity_count = random.randint(2, 4)

        for _ in range(activity_count):

            activity = random.choice(ACTIVITIES)

            if risk <= 25:

                status = "Completed"
                result = "Successful"

            elif risk <= 70:

                status = "Completed"
                result = "Successful"

            else:

                status = "In Progress"
                result = "Pending Validation"

            cursor.execute("""

            INSERT INTO endpoint_engineering(

                device_id,
                activity_name,
                activity_type,
                status,
                tool_name,
                engineer,
                started_time,
                completed_time,
                result,
                notes

            )

            VALUES(

                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                datetime('now'),
                datetime('now'),
                ?,
                ?

            )

            """,

            (

                device["device_id"],
                activity[0],
                activity[1],
                status,
                activity[2],
                "Darshit Goyal",
                result,
                "Generated by EESOP Enterprise Simulator"

            ))

            total += 1

    conn.commit()
    conn.close()

    print(f"{total} engineering activities created successfully.")


if __name__ == "__main__":
    seed_engineering()