import random

from database.connection import get_connection


ACTIONS = [
    (
        "Run Microsoft Defender Full Scan",
        "Threat Response",
        "Microsoft Defender"
    ),
    (
        "Isolate Endpoint",
        "Containment",
        "Microsoft Defender"
    ),
    (
        "Restart CrowdStrike Sensor",
        "Endpoint Maintenance",
        "CrowdStrike Falcon"
    ),
    (
        "Rotate BitLocker Recovery Key",
        "Encryption",
        "Microsoft Intune"
    ),
    (
        "Collect Endpoint Logs",
        "Investigation",
        "Microsoft Defender"
    ),
    (
        "Force Intune Policy Sync",
        "Compliance",
        "Microsoft Intune"
    ),
    (
        "Restart Device",
        "Maintenance",
        "Windows"
    )
]


def seed_actions():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT
            device_id,
            risk_score
        FROM devices
        ORDER BY device_id
    """)

    devices = cursor.fetchall()

    total = 0

    for device in devices:

        risk = device["risk_score"]

        if risk <= 25:
            action_count = random.randint(0, 1)

        elif risk <= 70:
            action_count = random.randint(1, 2)

        else:
            action_count = random.randint(2, 4)

        for _ in range(action_count):

            action = random.choice(ACTIONS)

            if risk <= 25:

                status = "Completed"
                result = "Successful"

            elif risk <= 70:

                status = "Completed"
                result = "Successful"

            else:

                status = "Pending"
                result = "Awaiting Validation"

            cursor.execute("""

            INSERT INTO endpoint_actions(

                device_id,
                action_name,
                action_category,
                requested_by,
                requested_time,
                tool_name,
                status,
                completed_time,
                result,
                remarks

            )

            VALUES(

                ?,
                ?,
                ?,
                ?,
                datetime('now'),
                ?,
                ?,
                datetime('now'),
                ?,
                ?

            )

            """,

            (

                device["device_id"],
                action[0],
                action[1],
                "SOC Analyst",
                action[2],
                status,
                result,
                "Generated by EESOP Enterprise Simulator"

            ))

            total += 1

    conn.commit()
    conn.close()

    print(f"{total} endpoint actions created successfully.")


if __name__ == "__main__":
    seed_actions()